# Generated by Django 5.0.6 on 2024-12-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_subscriber_learner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='learner',
        ),
    ]
