# Generated by Django 4.2.15 on 2024-09-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
