# Generated by Django 5.0.6 on 2024-10-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chathistory_input_tokens_chathistory_output_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
