# Generated by Django 5.0.6 on 2024-09-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_learner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
