# Generated by Django 5.0.6 on 2024-09-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_feedback_alter_quiz_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='user_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
