# Generated by Django 5.0.6 on 2024-10-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_questions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
