# Generated by Django 5.0.6 on 2024-07-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learner", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learner",
            old_name="fullname",
            new_name="fistname",
        ),
        migrations.AddField(
            model_name="learner",
            name="lastname",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
