# Generated by Django 5.0.6 on 2024-07-06 02:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learner", "0002_rename_fullname_learner_fistname_learner_lastname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learner",
            old_name="fistname",
            new_name="firstname",
        ),
    ]
