# Generated by Django 5.0.6 on 2024-07-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learner", "0003_rename_fistname_learner_firstname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learner",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="learner",
            name="lastname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="learner",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
