# Generated by Django 5.0.6 on 2024-09-24 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0005_alter_learner_firstname_alter_learner_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_bot_calls', models.IntegerField(default=0)),
                ('pastpaper_bot_calls', models.IntegerField(default=0)),
                ('historical_bot_calls', models.IntegerField(default=0)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
