# Generated by Django 5.0.6 on 2024-09-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0006_learnerquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
