# Generated by Django 5.0.6 on 2024-09-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0007_learner_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerquota',
            name='last_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
