# Generated by Django 5.0.6 on 2024-09-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0008_learnerquota_last_reset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerquota',
            name='initial_general_bot_quota',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='learnerquota',
            name='initial_historical_bot_quota',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='learnerquota',
            name='initial_pastpaper_bot_quota',
            field=models.IntegerField(default=2),
        ),
    ]
