# Generated by Django 5.0.6 on 2024-09-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0009_learnerquota_initial_general_bot_quota_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnerquota',
            old_name='initial_general_bot_quota',
            new_name='general_bot_quota',
        ),
        migrations.RenameField(
            model_name='learnerquota',
            old_name='initial_historical_bot_quota',
            new_name='historical_bot_quota',
        ),
        migrations.RenameField(
            model_name='learnerquota',
            old_name='initial_pastpaper_bot_quota',
            new_name='pastpaper_bot_quota',
        ),
    ]
