# Generated by Django 5.0.6 on 2024-10-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0010_rename_initial_general_bot_quota_learnerquota_general_bot_quota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerquota',
            name='general_bot_quota',
            field=models.IntegerField(default=15),
        ),
    ]
