# Generated by Django 5.0.6 on 2024-10-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0011_alter_learnerquota_general_bot_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerquota',
            name='pastpaper_bot_quota',
            field=models.IntegerField(default=15),
        ),
    ]
