# Generated by Django 5.0.6 on 2024-10-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0012_alter_learnerquota_pastpaper_bot_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerquota',
            name='historical_bot_quota',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='learnerquota',
            name='pastpaper_bot_quota',
            field=models.IntegerField(default=2),
        ),
    ]
