# Generated by Django 5.0.6 on 2024-12-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0013_alter_learnerquota_historical_bot_quota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerquota',
            name='pastpaper_bot_quota',
            field=models.IntegerField(default=10),
        ),
    ]
