# Generated by Django 5.0.6 on 2024-12-28 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0014_alter_learnerquota_pastpaper_bot_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='learner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
