# Generated by Django 5.0.6 on 2025-01-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0015_learner_verification_token_alter_learner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='reset_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='reset_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
