# Generated by Django 5.0.6 on 2025-01-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0016_learner_reset_token_learner_reset_token_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerquota',
            name='general_bot_quota',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='learnerquota',
            name='historical_bot_quota',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='learnerquota',
            name='pastpaper_bot_quota',
            field=models.IntegerField(default=5),
        ),
    ]
