# Generated by Django 5.0.6 on 2025-02-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0018_interest_learnerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerprofile',
            name='interests',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='interests',
            field=models.TextField(blank=True, help_text="Store interests as a comma-separated list e.g., 'cricket, singing, dancing'", null=True),
        ),
    ]
