# Generated by Django 5.0.6 on 2025-02-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0019_remove_learnerprofile_interests_delete_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='grade',
            field=models.CharField(blank=True, help_text="Student's current grade e.g., 'Below grade 6', '6', '7', '8', '9', '10', 'O/L', 'A/L', 'Above A/L'", max_length=10, null=True),
        ),
    ]
