# Generated by Django 5.0.6 on 2025-02-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0020_learnerprofile_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='calling_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
