# Generated by Django 5.0.6 on 2025-02-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0021_learnerprofile_calling_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerquota',
            name='general_bot_quota',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='learnerquota',
            name='historical_bot_quota',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='learnerquota',
            name='pastpaper_bot_quota',
            field=models.IntegerField(default=15),
        ),
    ]
