# Generated by Django 4.2.15 on 2024-09-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastpaper', '0002_rename_learner_id_pastpaperchat_learner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaperchat',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pastpaperchat',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
