# Generated by Django 5.0.6 on 2024-10-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical', '0002_historicalchathistory_input_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalchat',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
